from memgpt.agent import Agent
import json

def get_container_logs(self: Agent, container_id: str) -> str:
    """
    Retrieves the logs from the Docker container after code execution.

    Args:
        container_id (str): The ID of the running Docker container.

    Returns:
        str: The logs generated by the Docker container.
    """
    import docker
    try:
        client = docker.from_env()
        container = client.containers.get(container_id)
        
        # Retrieve logs
        logs = container.logs().decode('utf-8')
        return logs
    except Exception as e:
        return f"Error retrieving logs: {str(e)}"


def stop_docker_container(self: Agent, container_id: str) -> str:
    """
    Stops and removes the Docker container after execution.

    Args:
        container_id (str): The ID of the running Docker container.

    Returns:
        str: Status message indicating the result of the stop action.
    """
    import docker
    try:
        client = docker.from_env()
        container = client.containers.get(container_id)
        
        # Stop and remove the container
        container.stop()
        return f"Container {container_id} stopped and removed."
    except Exception as e:
        return f"Error stopping container: {str(e)}"
